site_name: ${{values.component_id | dump}}
site_description: ${{values.description | dump}}

repo_url: https://github.com/${{ values.destination.owner }}/${{ values.component_id }}


nav:
  - Introduction: index.md
  - Build & Run: build.md
  - Deploy: deployment.md

plugins:
  - techdocs-core
